### ISSUE TITLE
sudocommands.py autostart crashes on Ubuntu 21.10 and 20.04

### ISSUE THREAD

**Issue by smiddy** [Slimbook-Team/slimbookbattery#60]
**Describe the bug**
Start Ubuntu 21.10 with installed (and autostarted) Slimbook battery

**To Reproduce**
1. Install slimbook
2. Login to your account
3. Ubuntu notifies about a crash (every time)
4. App works nevertheless

**Desktop (please complete the following information):**
 - OS: Xubuntu 64 bit
 - Version: 21.10
 - Desktop Environment: XFCE 4.16

**Additional context**
```
ProblemType: Crash
Date: Fri Dec 24 14:06:35 2021
ExecutablePath: /usr/share/slimbookbattery/src/sudocommands.py
ExecutableTimestamp: 1633429444
InterpreterPath: /usr/bin/python3.9
ProcCmdline: python3 /usr/share/slimbookbattery/src/sudocommands.py autostart
ProcCwd: /root
ProcEnviron:
 SHELL=/bin/sh
 LC_ADDRESS=de_CH.UTF-8
 LC_NAME=de_CH.UTF-8
 LC_MONETARY=de_CH.UTF-8
 LC_PAPER=de_CH.UTF-8
 LANG=en_US.UTF-8
 LC_IDENTIFICATION=de_CH.UTF-8
 LC_TELEPHONE=de_CH.UTF-8
 LC_MEASUREMENT=de_CH.UTF-8
 LC_TIME=de_CH.UTF-8
 PATH=(custom, no user)
 LC_NUMERIC=de_CH.UTF-8
ProcMaps:
 00400000-0041f000 r--p 00000000 fd:01 12058769                           /usr/bin/python3.9
 0041f000-00698000 r-xp 0001f000 fd:01 12058769                           /usr/bin/python3.9
 00698000-008e6000 r--p 00298000 fd:01 12058769                           /usr/bin/python3.9
 008e6000-008e7000 r--p 004e5000 fd:01 12058769                           /usr/bin/python3.9
 008e7000-0092e000 rw-p 004e6000 fd:01 12058769                           /usr/bin/python3.9
 0092e000-00952000 rw-p 00000000 00:00 0 
 0165b000-018e4000 rw-p 00000000 00:00 0                                  [heap]
 7f574c6ab000-7f574c87c000 rw-p 00000000 00:00 0 
 7f574c87c000-7f574c898000 r--p 00000000 fd:01 12059142                   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
 7f574c898000-7f574c8ee000 r-xp 0001c000 fd:01 12059142                   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
 7f574c8ee000-7f574c906000 r--p 00072000 fd:01 12059142                   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
 7f574c906000-7f574c907000 ---p 0008a000 fd:01 12059142                   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
 7f574c907000-7f574c910000 r--p 0008a000 fd:01 12059142                   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
 7f574c910000-7f574c914000 rw-p 00093000 fd:01 12059142                   /usr/lib/x86_64-linux-gnu/libssl.so.1.1
 7f574c914000-7f574c923000 r--p 00000000 fd:01 12583443                   /usr/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so
 7f574c923000-7f574c92e000 r-xp 0000f000 fd:01 12583443                   /usr/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so
 7f574c92e000-7f574c93a000 r--p 0001a000 fd:01 12583443                   /usr/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so
 7f574c93a000-7f574c93b000 r--p 00025000 fd:01 12583443                   /usr/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so
 7f574c93b000-7f574c942000 rw-p 00026000 fd:01 12583443                   /usr/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so
 7f574c942000-7f574ca43000 rw-p 00000000 00:00 0 
 7f574ca43000-7f574cabb000 r--p 00000000 fd:01 12059140                   /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
 7f574cabb000-7f574cc5e000 r-xp 00078000 fd:01 12059140                   /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
 7f574cc5e000-7f574ccec000 r--p 0021b000 fd:01 12059140                   /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
 7f574ccec000-7f574cd18000 r--p 002a8000 fd:01 12059140                   /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
 7f574cd18000-7f574cd1a000 rw-p 002d4000 fd:01 12059140                   /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
 7f574cd1a000-7f574cd1e000 rw-p 00000000 00:00 0 
 7f574cd26000-7f574cd28000 r--p 00000000 fd:01 12583389                   /usr/lib/python3.9/lib-dynload/_json.cpython-39-x86_64-linux-gnu.so
 7f574cd28000-7f574cd2f000 r-xp 00002000 fd:01 12583389                   /usr/lib/python3.9/lib-dynload/_json.cpython-39-x86_64-linux-gnu.so
 7f574cd2f000-7f574cd31000 r--p 00009000 fd:01 12583389                   /usr/lib/python3.9/lib-dynload/_json.cpython-39-x86_64-linux-gnu.so
 7f574cd31000-7f574cd32000 r--p 0000a000 fd:01 12583389                   /usr/lib/python3.9/lib-dynload/_json.cpython-39-x86_64-linux-gnu.so
 7f574cd32000-7f574cd33000 rw-p 0000b000 fd:01 12583389                   /usr/lib/python3.9/lib-dynload/_json.cpython-39-x86_64-linux-gnu.so
 7f574cd33000-7f574ce73000 rw-p 00000000 00:00 0 
 7f574ce73000-7f574ce78000 r--p 00000000 fd:01 12058832                   /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
 7f574ce78000-7f574ce8e000 r-xp 00005000 fd:01 12058832                   /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
 7f574ce8e000-7f574ce98000 r--p 0001b000 fd:01 12058832                   /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
 7f574ce98000-7f574ce99000 ---p 00025000 fd:01 12058832                   /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
 7f574ce99000-7f574ce9a000 r--p 00025000 fd:01 12058832                   /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
 7f574ce9a000-7f574ce9b000 rw-p 00026000 fd:01 12058832                   /usr/lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
 7f574ce9b000-7f574ce9d000 r--p 00000000 fd:01 12065124                   /usr/lib/x86_64-linux-gnu/libxxhash.so.0.8.0
 7f574ce9d000-7f574ceae000 r-xp 00002000 fd:01 12065124                   /usr/lib/x86_64-linux-gnu/libxxhash.so.0.8.0
 7f574ceae000-7f574ceb0000 r--p 00013000 fd:01 12065124                   /usr/lib/x86_64-linux-gnu/libxxhash.so.0.8.0
 7f574ceb0000-7f574ceb1000 r--p 00014000 fd:01 12065124                   /usr/lib/x86_64-linux-gnu/libxxhash.so.0.8.0
 7f574ceb1000-7f574ceb2000 rw-p 00015000 fd:01 12065124                   /usr/lib/x86_64-linux-gnu/libxxhash.so.0.8.0
 7f574ceb2000-7f574cebe000 r--p 00000000 fd:01 12064462                   /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
 7f574cebe000-7f574cf94000 r-xp 0000c000 fd:01 12064462                   /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
 7f574cf94000-7f574cfcd000 r--p 000e2000 fd:01 12064462                   /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
 7f574cfcd000-7f574cfcf000 r--p 0011a000 fd:01 12064462                   /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
 7f574cfcf000-7f574cfd4000 rw-p 0011c000 fd:01 12064462                   /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
 7f574cfd4000-7f574cfd5000 rw-p 00000000 00:00 0 
 7f574cfd5000-7f574cfe6000 r--p 00000000 fd:01 12059224                   /usr/lib/x86_64-linux-gnu/libsystemd.so.0.31.0
 7f574cfe6000-7f574d062000 r-xp 00011000 fd:01 12059224                   /usr/lib/x86_64-linux-gnu/libsystemd.so.0.31.0
 7f574d062000-7f574d088000 r--p 0008d000 fd:01 12059224                   /usr/lib/x86_64-linux-gnu/libsystemd.so.0.31.0
 7f574d088000-7f574d08b000 r--p 000b2000 fd:01 12059224                   /usr/lib/x86_64-linux-gnu/libsystemd.so.0.31.0
 7f574d08b000-7f574d08c000 rw-p 000b5000 fd:01 12059224                   /usr/lib/x86_64-linux-gnu/libsystemd.so.0.31.0
 7f574d08c000-7f574d08d000 rw-p 00000000 00:00 0 
 7f574d08d000-7f574d091000 r--p 00000000 fd:01 12059633                   /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1
 7f574d091000-7f574d0aa000 r-xp 00004000 fd:01 12059633                   /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1
 7f574d0aa000-7f574d0b3000 r--p 0001d000 fd:01 12059633                   /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1
 7f574d0b3000-7f574d0b4000 ---p 00026000 fd:01 12059633                   /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1
 7f574d0b4000-7f574d0b5000 r--p 00026000 fd:01 12059633                   /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1
 7f574d0b5000-7f574d0b6000 rw-p 00027000 fd:01 12059633                   /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1
 7f574d0b6000-7f574d0c0000 r--p 00000000 fd:01 12059341                   /usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
 7f574d0c0000-7f574d170000 r-xp 0000a000 fd:01 12059341                   /usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
 7f574d170000-7f574d181000 r--p 000ba000 fd:01 12059341                   /usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
 7f574d181000-7f574d182000 r--p 000ca000 fd:01 12059341                   /usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
 7f574d182000-7f574d183000 rw-p 000cb000 fd:01 12059341                   /usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
 7f574d183000-7f574d185000 r--p 00000000 fd:01 12059231                   /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
 7f574d185000-7f574d19e000 r-xp 00002000 fd:01 12059231                   /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
 7f574d19e000-7f574d1a0000 r--p 0001b000 fd:01 12059231                   /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
 7f574d1a0000-7f574d1a1000 ---p 0001d000 fd:01 12059231                   /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
 7f574d1a1000-7f574d1a2000 r--p 0001d000 fd:01 12059231                   /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
 7f574d1a2000-7f574d1a3000 rw-p 0001e000 fd:01 12059231                   /usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3
 7f574d1a3000-7f574d1a6000 r--p 00000000 fd:01 12060178                   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
 7f574d1a6000-7f574d1b8000 r-xp 00003000 fd:01 12060178                   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
 7f574d1b8000-7f574d1bb000 r--p 00015000 fd:01 12060178                   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
 7f574d1bb000-7f574d1bc000 r--p 00017000 fd:01 12060178                   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
 7f574d1bc000-7f574d1bd000 rw-p 00018000 fd:01 12060178                   /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
 7f574d1bd000-7f574d256000 r--p 00000000 fd:01 12058788                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29
 7f574d256000-7f574d359000 r-xp 00099000 fd:01 12058788                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29
 7f574d359000-7f574d3c5000 r--p 0019c000 fd:01 12058788                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29
 7f574d3c5000-7f574d3d0000 r--p 00207000 fd:01 12058788                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29
 7f574d3d0000-7f574d3d3000 rw-p 00212000 fd:01 12058788                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29
 7f574d3d3000-7f574d3d6000 rw-p 00000000 00:00 0 
 7f574d3d6000-7f574d40c000 r--p 00000000 fd:01 12059393                   /usr/lib/x86_64-linux-gnu/libapt-pkg.so.6.0.0
 7f574d40c000-7f574d545000 r-xp 00036000 fd:01 12059393                   /usr/lib/x86_64-linux-gnu/libapt-pkg.so.6.0.0
 7f574d545000-7f574d58c000 r--p 0016f000 fd:01 12059393                   /usr/lib/x86_64-linux-gnu/libapt-pkg.so.6.0.0
 7f574d58c000-7f574d593000 r--p 001b5000 fd:01 12059393                   /usr/lib/x86_64-linux-gnu/libapt-pkg.so.6.0.0
 7f574d593000-7f574d594000 rw-p 001bc000 fd:01 12059393                   /usr/lib/x86_64-linux-gnu/libapt-pkg.so.6.0.0
 7f574d594000-7f574d5a9000 r--p 00000000 fd:01 12453212                   /usr/lib/python3/dist-packages/apt_pkg.cpython-39-x86_64-linux-gnu.so
 7f574d5a9000-7f574d5c8000 r-xp 00015000 fd:01 12453212                   /usr/lib/python3/dist-packages/apt_pkg.cpython-39-x86_64-linux-gnu.so
 7f574d5c8000-7f574d5df000 r--p 00034000 fd:01 12453212                   /usr/lib/python3/dist-packages/apt_pkg.cpython-39-x86_64-linux-gnu.so
 7f574d5df000-7f574d5e1000 r--p 0004a000 fd:01 12453212                   /usr/lib/python3/dist-packages/apt_pkg.cpython-39-x86_64-linux-gnu.so
 7f574d5e1000-7f574d5ea000 rw-p 0004c000 fd:01 12453212                   /usr/lib/python3/dist-packages/apt_pkg.cpython-39-x86_64-linux-gnu.so
 7f574d5ea000-7f574d5f0000 r--p 00000000 fd:01 12059463                   /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
 7f574d5f0000-7f574d61e000 r-xp 00006000 fd:01 12059463                   /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
 7f574d61e000-7f574d62d000 r--p 00034000 fd:01 12059463                   /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
 7f574d62d000-7f574d631000 r--p 00042000 fd:01 12059463                   /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
 7f574d631000-7f574d632000 rw-p 00046000 fd:01 12059463                   /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
 7f574d632000-7f574d6b2000 rw-p 00000000 00:00 0 
 7f574d6bb000-7f574d73b000 rw-p 00000000 00:00 0 
 7f574d73b000-7f574d73e000 r--p 00000000 fd:01 12059262                   /usr/lib/x86_64-linux-gnu/liblzma.so.5.2.5
 7f574d73e000-7f574d759000 r-xp 00003000 fd:01 12059262                   /usr/lib/x86_64-linux-gnu/liblzma.so.5.2.5
 7f574d759000-7f574d764000 r--p 0001e000 fd:01 12059262                   /usr/lib/x86_64-linux-gnu/liblzma.so.5.2.5
 7f574d764000-7f574d765000 r--p 00028000 fd:01 12059262                   /usr/lib/x86_64-linux-gnu/liblzma.so.5.2.5
 7f574d765000-7f574d766000 rw-p 00029000 fd:01 12059262                   /usr/lib/x86_64-linux-gnu/liblzma.so.5.2.5
 7f574d770000-7f574d773000 r--p 00000000 fd:01 12065062                   /usr/lib/x86_64-linux-gnu/libcap.so.2.44
 7f574d773000-7f574d777000 r-xp 00003000 fd:01 12065062                   /usr/lib/x86_64-linux-gnu/libcap.so.2.44
 7f574d777000-7f574d779000 r--p 00007000 fd:01 12065062                   /usr/lib/x86_64-linux-gnu/libcap.so.2.44
 7f574d779000-7f574d77a000 r--p 00008000 fd:01 12065062                   /usr/lib/x86_64-linux-gnu/libcap.so.2.44
 7f574d77a000-7f574d77b000 rw-p 00009000 fd:01 12065062                   /usr/lib/x86_64-linux-gnu/libcap.so.2.44
 7f574d77b000-7f574d77d000 r--p 00000000 fd:01 12058760                   /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
 7f574d77d000-7f574d78a000 r-xp 00002000 fd:01 12058760                   /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
 7f574d78a000-7f574d78c000 r--p 0000f000 fd:01 12058760                   /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
 7f574d78c000-7f574d78d000 r--p 00010000 fd:01 12058760                   /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
 7f574d78d000-7f574d78e000 rw-p 00011000 fd:01 12058760                   /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
 7f574d797000-7f574d79a000 r--p 00000000 fd:01 12583391                   /usr/lib/python3.9/lib-dynload/_lzma.cpython-39-x86_64-linux-gnu.so
 7f574d79a000-7f574d79e000 r-xp 00003000 fd:01 12583391                   /usr/lib/python3.9/lib-dynload/_lzma.cpython-39-x86_64-linux-gnu.so
 7f574d79e000-7f574d7a1000 r--p 00007000 fd:01 12583391                   /usr/lib/python3.9/lib-dynload/_lzma.cpython-39-x86_64-linux-gnu.so
 7f574d7a1000-7f574d7a2000 r--p 00009000 fd:01 12583391                   /usr/lib/python3.9/lib-dynload/_lzma.cpython-39-x86_64-linux-gnu.so
 7f574d7a2000-7f574d7a3000 rw-p 0000a000 fd:01 12583391                   /usr/lib/python3.9/lib-dynload/_lzma.cpython-39-x86_64-linux-gnu.so
 7f574d7a3000-7f574d923000 rw-p 00000000 00:00 0 
 7f574d92c000-7f574d930000 r--p 00000000 fd:01 12583441                   /usr/lib/python3.9/lib-dynload/_hashlib.cpython-39-x86_64-linux-gnu.so
 7f574d930000-7f574d938000 r-xp 00004000 fd:01 12583441                   /usr/lib/python3.9/lib-dynload/_hashlib.cpython-39-x86_64-linux-gnu.so
 7f574d938000-7f574d93c000 r--p 0000c000 fd:01 12583441                   /usr/lib/python3.9/lib-dynload/_hashlib.cpython-39-x86_64-linux-gnu.so
 7f574d93c000-7f574d93d000 r--p 0000f000 fd:01 12583441                   /usr/lib/python3.9/lib-dynload/_hashlib.cpython-39-x86_64-linux-gnu.so
 7f574d93d000-7f574d93f000 rw-p 00010000 fd:01 12583441                   /usr/lib/python3.9/lib-dynload/_hashlib.cpython-39-x86_64-linux-gnu.so
 7f574d93f000-7f574d942000 r--p 00000000 fd:01 12583439                   /usr/lib/python3.9/lib-dynload/termios.cpython-39-x86_64-linux-gnu.so
 7f574d942000-7f574d943000 r-xp 00003000 fd:01 12583439                   /usr/lib/python3.9/lib-dynload/termios.cpython-39-x86_64-linux-gnu.so
 7f574d943000-7f574d945000 r--p 00004000 fd:01 12583439                   /usr/lib/python3.9/lib-dynload/termios.cpython-39-x86_64-linux-gnu.so
 7f574d945000-7f574d946000 r--p 00005000 fd:01 12583439                   /usr/lib/python3.9/lib-dynload/termios.cpython-39-x86_64-linux-gnu.so
 7f574d946000-7f574d948000 rw-p 00006000 fd:01 12583439                   /usr/lib/python3.9/lib-dynload/termios.cpython-39-x86_64-linux-gnu.so
 7f574d948000-7f574da88000 rw-p 00000000 00:00 0 
 7f574da88000-7f574e2d2000 r--p 00000000 fd:01 12060859                   /usr/lib/locale/locale-archive
 7f574e2d2000-7f574e2d4000 rw-p 00000000 00:00 0 
 7f574e2d4000-7f574e300000 r--p 00000000 fd:01 12060833                   /usr/lib/x86_64-linux-gnu/libc.so.6
 7f574e300000-7f574e494000 r-xp 0002c000 fd:01 12060833                   /usr/lib/x86_64-linux-gnu/libc.so.6
 7f574e494000-7f574e4e8000 r--p 001c0000 fd:01 12060833                   /usr/lib/x86_64-linux-gnu/libc.so.6
 7f574e4e8000-7f574e4e9000 ---p 00214000 fd:01 12060833                   /usr/lib/x86_64-linux-gnu/libc.so.6
 7f574e4e9000-7f574e4ec000 r--p 00214000 fd:01 12060833                   /usr/lib/x86_64-linux-gnu/libc.so.6
 7f574e4ec000-7f574e4ef000 rw-p 00217000 fd:01 12060833                   /usr/lib/x86_64-linux-gnu/libc.so.6
 7f574e4ef000-7f574e4fc000 rw-p 00000000 00:00 0 
 7f574e4fc000-7f574e4fe000 r--p 00000000 fd:01 12059137                   /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
 7f574e4fe000-7f574e50f000 r-xp 00002000 fd:01 12059137                   /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
 7f574e50f000-7f574e515000 r--p 00013000 fd:01 12059137                   /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
 7f574e515000-7f574e516000 ---p 00019000 fd:01 12059137                   /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
 7f574e516000-7f574e517000 r--p 00019000 fd:01 12059137                   /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
 7f574e517000-7f574e518000 rw-p 0001a000 fd:01 12059137                   /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
 7f574e518000-7f574e51c000 r--p 00000000 fd:01 12058824                   /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
 7f574e51c000-7f574e53a000 r-xp 00004000 fd:01 12058824                   /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
 7f574e53a000-7f574e544000 r--p 00022000 fd:01 12058824                   /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
 7f574e544000-7f574e545000 ---p 0002c000 fd:01 12058824                   /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
 7f574e545000-7f574e547000 r--p 0002c000 fd:01 12058824                   /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
 7f574e547000-7f574e548000 rw-p 0002e000 fd:01 12058824                   /usr/lib/x86_64-linux-gnu/libexpat.so.1.8.1
 7f574e548000-7f574e557000 r--p 00000000 fd:01 12060838                   /usr/lib/x86_64-linux-gnu/libm.so.6
 7f574e557000-7f574e5d1000 r-xp 0000f000 fd:01 12060838                   /usr/lib/x86_64-linux-gnu/libm.so.6
 7f574e5d1000-7f574e629000 r--p 00089000 fd:01 12060838                   /usr/lib/x86_64-linux-gnu/libm.so.6
 7f574e629000-7f574e62a000 ---p 000e1000 fd:01 12060838                   /usr/lib/x86_64-linux-gnu/libm.so.6
 7f574e62a000-7f574e62b000 r--p 000e1000 fd:01 12060838                   /usr/lib/x86_64-linux-gnu/libm.so.6
 7f574e62b000-7f574e62c000 rw-p 000e2000 fd:01 12060838                   /usr/lib/x86_64-linux-gnu/libm.so.6
 7f574e62c000-7f574e62e000 rw-p 00000000 00:00 0 
 7f574e62f000-7f574e630000 r--p 00000000 fd:01 12060854                   /usr/lib/x86_64-linux-gnu/libpthread.so.0
 7f574e630000-7f574e631000 r-xp 00001000 fd:01 12060854                   /usr/lib/x86_64-linux-gnu/libpthread.so.0
 7f574e631000-7f574e632000 r--p 00002000 fd:01 12060854                   /usr/lib/x86_64-linux-gnu/libpthread.so.0
 7f574e632000-7f574e633000 r--p 00002000 fd:01 12060854                   /usr/lib/x86_64-linux-gnu/libpthread.so.0
 7f574e633000-7f574e634000 rw-p 00003000 fd:01 12060854                   /usr/lib/x86_64-linux-gnu/libpthread.so.0
 7f574e634000-7f574e636000 r--p 00000000 fd:01 12583068                   /usr/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so
 7f574e636000-7f574e638000 r-xp 00002000 fd:01 12583068                   /usr/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so
 7f574e638000-7f574e639000 r--p 00004000 fd:01 12583068                   /usr/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so
 7f574e639000-7f574e63a000 ---p 00005000 fd:01 12583068                   /usr/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so
 7f574e63a000-7f574e63b000 r--p 00005000 fd:01 12583068                   /usr/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so
 7f574e63b000-7f574e63c000 rw-p 00006000 fd:01 12583068                   /usr/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so
 7f574e63c000-7f574e643000 r--s 00000000 fd:01 12715937                   /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
 7f574e643000-7f574e644000 r--p 00000000 fd:01 12060731                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
 7f574e644000-7f574e66c000 r-xp 00001000 fd:01 12060731                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
 7f574e66c000-7f574e676000 r--p 00029000 fd:01 12060731                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
 7f574e676000-7f574e678000 r--p 00032000 fd:01 12060731                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
 7f574e678000-7f574e67a000 rw-p 00034000 fd:01 12060731                   /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
 7fff62926000-7fff62947000 rw-p 00000000 00:00 0                          [stack]
 7fff62967000-7fff6296b000 r--p 00000000 00:00 0                          [vvar]
 7fff6296b000-7fff6296d000 r-xp 00000000 00:00 0                          [vdso]
 ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
ProcStatus:
 Name:	python3
 Umask:	0022
 State:	R (running)
 Tgid:	1099
 Ngid:	0
 Pid:	1099
 PPid:	1095
 TracerPid:	0
 Uid:	0	0	0	0
 Gid:	0	0	0	0
 FDSize:	256
 Groups:	0 
 NStgid:	1099
 NSpid:	1099
 NSpgid:	1094
 NSsid:	1094
 VmPeak:	   40588 kB
 VmSize:	   40588 kB
 VmLck:	       0 kB
 VmPin:	       0 kB
 VmHWM:	   23680 kB
 VmRSS:	   23680 kB
 RssAnon:	   11440 kB
 RssFile:	   12240 kB
 RssShmem:	       0 kB
 VmData:	   11368 kB
 VmStk:	     132 kB
 VmExe:	    2532 kB
 VmLib:	    9872 kB
 VmPTE:	     112 kB
 VmSwap:	       0 kB
 HugetlbPages:	       0 kB
 CoreDumping:	0
 THP_enabled:	1
 Threads:	1
 SigQ:	23/47124
 SigPnd:	0000000000000000
 ShdPnd:	0000000000000000
 SigBlk:	0000000000000000
 SigIgn:	0000000001001000
 SigCgt:	0000000000000002
 CapInh:	0000000000000000
 CapPrm:	000001ffffffffff
 CapEff:	000001ffffffffff
 CapBnd:	000001ffffffffff
 CapAmb:	0000000000000000
 NoNewPrivs:	0
 Seccomp:	0
 Seccomp_filters:	0
 Speculation_Store_Bypass:	thread vulnerable
 SpeculationIndirectBranch:	conditional enabled
 Cpus_allowed:	ff
 Cpus_allowed_list:	0-7
 Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
 Mems_allowed_list:	0
 voluntary_ctxt_switches:	170
 nonvoluntary_ctxt_switches:	145
PythonArgs: ['/usr/share/slimbookbattery/src/sudocommands.py', 'autostart']
Traceback:
 Traceback (most recent call last):
   File "/usr/share/slimbookbattery/src/sudocommands.py", line 618, in <module>
     main(sys.argv)
   File "/usr/share/slimbookbattery/src/sudocommands.py", line 131, in main
     battery_mode = config.get('CONFIGURATION', 'modo_actual')
   File "/usr/lib/python3.9/configparser.py", line 781, in get
     d = self._unify_values(section, vars)
   File "/usr/lib/python3.9/configparser.py", line 1152, in _unify_values
     raise NoSectionError(section) from None
 configparser.NoSectionError: No section: 'CONFIGURATION'
UserGroups: N/A
```

**Comment by smiddy** [comment]
The same problem occurs on Ubuntu 20.04.3

**Comment by slimbook** [comment]
#80
