### ISSUE TITLE
Laptop reboots as "reboot" user, cron email sent with error in sudocommands.py

### ISSUE THREAD

**Issue by doctorlard** [Slimbook-Team/slimbookbattery#80]
**Describe the bug**

When the laptop reboots, the cron daemon (systemd?) tries to run something in slimbookbattery as the special "reboot" user, and an exception is thrown in line 140 of `sudocommands.py`. The root source is because the reboot user does not have a slimbook config file in its `HOMEDIR` (because it does not have a HOME directory defined), so the `config` set up at line 79 silently returns an empty result. Thus, there is no expected `CONFIGURATION` section:

```
2022-08-24 12:19:27,222 - reboot - <module>:73 - DEBUG - ******************************************************************************
2022-08-24 12:19:27,222 - reboot - <module>:75 - INFO - [6;30;42mSlimbookBattery-Commandline, executed as: reboot[0m
2022-08-24 12:19:27,222 - reboot - <module>:77 - DEBUG - Username: reboot - Homedir: ~reboot
2022-08-24 12:19:27,222 - reboot - main:136 - DEBUG - Arguments:  autostart
Using  /etc/tlp.conf
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/sudocommands.py", line 571, in <module>
    main(sys.argv)
  File "/usr/share/slimbookbattery/src/sudocommands.py", line 140, in main
    battery_mode = config.get('CONFIGURATION', 'modo_actual')
  File "/usr/lib/python3.10/configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'CONFIGURATION'
```
The reboot user is special and does not have a home directory:
```
# ls ~reboot
ls: cannot access '~reboot': No such file or directory
#
```

**To Reproduce**
1. Install slimbookbattery 4.0.7 beta on Ubuntu 22.04
2. set up your machine to send cron errors to your email address
3. reboot
4. See cron error message in your email

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: Slimbook Battery 4.0.7 beta

**Expected behavior (Optional)**
Special handling of whatever is going on to either ignore anything trying to be run as the reboot user, or use some sensible default, e.g. fall back to the config in `/etc/tlp.conf` if the configuration is not found.

**Comment by MarSlimbook** [comment]
This was fixed sometime ago
