### ISSUE TITLE
Some toggles have no effect

### ISSUE THREAD

**Issue by Nationalgeographic** [Slimbook-Team/slimbookbattery#94]
**Describe the bug**
When toggling "Bluetooth does not boot on start"  to on and rebooting, BT  still turned on after bootup. I even removed Slimbookbattery, removed cache and tried a clean install, but with no effect. System is on Manjaro Gnome.

**To Reproduce**
1. Go to 'Engery Saving / Balanced / Maximum Perfomance' register cards/tabs 
2. Click on 'Bluetooth does not boot on start'
3. Scroll down to 'press accept'
4. reboot
5. 5ee no effect.

**Desktop (please complete the following information):**
 - OS:  Manjaro
 - Version: 6.0.15-1-MANJARO (Kernel)
 - Desktop Environment: Gnome

**Expected behavior (Optional)**
Bluetooth should be turned off.

**Comment by vtronko** [comment]
Same, can't save any settings in any profile, and profile itself always resets to "Balanced"

**Comment by MarSlimbook** [comment]
Give me some time to see how to make it work properly, specially compatibility between distros, are you also in Manjaro @vtronko?

**Comment by vtronko** [comment]
@MarSlimbook 
Hello, I've got a chance to reproduce the issue with settings again, this is what I see on start of preferences widget. Bear in mind, I'm in Energy Saving mode, but preferences window defaults to Balanced and doesn't read correct configuration values (not able to update them either).

```
Cannot open log file /var/slimbookbattery.log, using /tmp/slimbookbattery.log
Cannot open log file /var/slimbookbattery.log, using /tmp/slimbookbattery.log
2023-03-04 02:51:32,053 - 1692 - ERROR - Unexpected error
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 1690, in __init__
    self.set_ui()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 1905, in set_ui
    battery_page_grid = BatteryGrid(self)
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 501, in __init__
    super(BatteryGrid, self).__init__(parent, *args, **kwargs)
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 113, in __init__
    self.complete_values()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 592, in complete_values
    label.set_label(content)
TypeError: Argument 1 does not allow None as a value
Using  /etc/tlp.conf
2023-03-04 02:51:32,429 - jasper - <module>:73 - DEBUG - ******************************************************************************
2023-03-04 02:51:32,429 - jasper - <module>:75 - INFO - SlimbookBattery-Commandline, executed as: jasper
2023-03-04 02:51:32,429 - jasper - <module>:77 - DEBUG - Username: jasper - Homedir: /home/jasper
2023-03-04 02:51:32,430 - jasper - main:136 - DEBUG - Arguments:  restore
2023-03-04 02:51:32,430 - jasper - main:154 - INFO - Resetting modes conf
2023-03-04 02:51:32,431 - jasper - main:174 - INFO - Resetting Slimbook Battery's conf
2023-03-04 02:51:32,431 - jasper - main:177 - INFO - /usr/share/slimbookbattery/src/configuration/slimbookbattery.conf
2023-03-04 02:51:32,432 - jasper - main:216 - DEBUG - ******************************************************************************
<Gtk.Grid object at 0x7fa3b850d740 (GtkGrid at 0x560ca0ed8140)>
2023-03-04 02:51:33,055 - 1702 - ERROR - Unexpected error
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 1690, in __init__
    self.set_ui()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 1905, in set_ui
    battery_page_grid = BatteryGrid(self)
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 501, in __init__
    super(BatteryGrid, self).__init__(parent, *args, **kwargs)
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 113, in __init__
    self.complete_values()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 592, in complete_values
    label.set_label(content)
TypeError: Argument 1 does not allow None as a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 1700, in __init__
    self.set_ui()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 1905, in set_ui
    battery_page_grid = BatteryGrid(self)
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 501, in __init__
    super(BatteryGrid, self).__init__(parent, *args, **kwargs)
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 113, in __init__
    self.complete_values()
  File "/usr/share/slimbookbattery/src/slimbookbatterypreferences.py", line 592, in complete_values
    label.set_label(content)
TypeError: Argument 1 does not allow None as a value
```

I use Arch, not Manjaro. I also think this has nothing to do with distro, looks like some bug in UI that prevents setting up correct values.

**Comment by vtronko** [comment]
I want to bump this issue, because the bug is still there
