### ISSUE TITLE
slimbookbattery wont start on debian

### ISSUE THREAD

**Issue by Am0rphous** [Slimbook-Team/slimbookbattery#96]
**Describe the bug**
When installing the software from either the git repo or from deb files, the software won't start.

**To Reproduce**
1. Go to [this](https://software.opensuse.org//download.html?project=home%3ASlimbook%3ASlimbookBattery&package=slimbookbattery) link and download the deb file for debian
2. Install it with `sudo dpkg -i blabla.deb`
3. Open a new terminal window and run `slimbookbattery` or search and open it from the menu. It does not appear and there is no processes running named similar to slim: `ps aux|grep slim`. No error messages in the terminal either.

**Desktop (please complete the following information):**
 - OS: Kali GNU/Linux Rolling 
 - Version: 2022.4
 - Kernel: 6.0.0-kali6-amd64
 - Desktop Environment: GDM3

**Expected behavior (Optional)**
A tryicon is supposed to appear, but here is none.

**Additional context**
Installing it from the repo gives following output:
````
└─$ ./deploy.sh 

This script will install SlimbookBattery in your system (replacing previous
installation if exists).
Press ENTER to proceed, or CTRL-C to exit.


Checking and installing the following system dependencies (if needed)...
tlp tlp-rdw libnotify-bin cron gobject-introspection libayatana-appindicator3-1

...Done installing system dependencies!

Installing Python dependencies...
...Done installing Python dependencies!

Installing SlimbookBattery...

Removing previously installed resources...
[sudo] password for [REMOVED]: 
...Done removing previously installed resources!

Creating folder structure...
...Done creating folder structure!

Copying contents...
'bin/slimbookbattery' -> '/usr/bin/slimbookbattery'
'bin/slimbookbattery-pkexec' -> '/usr/bin/slimbookbattery-pkexec'
'bin/slimbookbattery' -> '/usr/share/slimbookbattery/bin/slimbookbattery'
'bin/slimbookbattery-pkexec' -> '/usr/share/slimbookbattery/bin/slimbookbattery-pkexec'
cp: cannot overwrite directory '/usr/share/slimbookbattery/changelog' with non-directory
'slimbookbattery.desktop' -> '/usr/share/applications/slimbookbattery.desktop'
'src/ac_power.py' -> '/usr/share/slimbookbattery/src/ac_power.py'
'src/check_config.py' -> '/usr/share/slimbookbattery/src/check_config.py'
'src/configuration' -> '/usr/share/slimbookbattery/src/configuration'
'src/configuration/custom' -> '/usr/share/slimbookbattery/src/configuration/custom'
'src/configuration/custom/ahorrodeenergia' -> '/usr/share/slimbookbattery/src/configuration/custom/ahorrodeenergia'
'src/configuration/custom/equilibrado' -> '/usr/share/slimbookbattery/src/configuration/custom/equilibrado'
'src/configuration/custom/maximorendimiento' -> '/usr/share/slimbookbattery/src/configuration/custom/maximorendimiento'
'src/configuration/default' -> '/usr/share/slimbookbattery/src/configuration/default'
'src/configuration/default/ahorrodeenergia' -> '/usr/share/slimbookbattery/src/configuration/default/ahorrodeenergia'
'src/configuration/default/equilibrado' -> '/usr/share/slimbookbattery/src/configuration/default/equilibrado'
'src/configuration/default/maximorendimiento' -> '/usr/share/slimbookbattery/src/configuration/default/maximorendimiento'
'src/configuration/default/tlp' -> '/usr/share/slimbookbattery/src/configuration/default/tlp'
'src/configuration/default/tlp/default-1.3.conf' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/default-1.3.conf'
'src/configuration/default/tlp/default-1.5.conf' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/default-1.5.conf'
'src/configuration/default/tlp/old_defaults' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/old_defaults'
'src/configuration/default/tlp/old_defaults/ahorrodeenergia' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/old_defaults/ahorrodeenergia'
'src/configuration/default/tlp/old_defaults/equilibrado' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/old_defaults/equilibrado'
'src/configuration/default/tlp/old_defaults/maximorendimiento' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/old_defaults/maximorendimiento'
'src/configuration/default/tlp/tlp-intrinsic-defaults.conf' -> '/usr/share/slimbookbattery/src/configuration/default/tlp/tlp-intrinsic-defaults.conf'
'src/configuration/slimbookbattery-autostart.desktop' -> '/usr/share/slimbookbattery/src/configuration/slimbookbattery-autostart.desktop'
'src/configuration/slimbookbattery.conf' -> '/usr/share/slimbookbattery/src/configuration/slimbookbattery.conf'
'src/css' -> '/usr/share/slimbookbattery/src/css'
'src/css/original-style.css' -> '/usr/share/slimbookbattery/src/css/original-style.css'
'src/css/system-style.css' -> '/usr/share/slimbookbattery/src/css/system-style.css'
'src/root' -> '/usr/share/slimbookbattery/src/root'
'src/service' -> '/usr/share/slimbookbattery/src/service'
'src/service/slimbookbattery.service' -> '/usr/share/slimbookbattery/src/service/slimbookbattery.service'
'src/service/slimbookbatteryservice.sh' -> '/usr/share/slimbookbattery/src/service/slimbookbatteryservice.sh'
'src/slimbookbattery-autostart.desktop' -> '/usr/share/slimbookbattery/src/slimbookbattery-autostart.desktop'
'src/slimbookbatteryindicator.py' -> '/usr/share/slimbookbattery/src/slimbookbatteryindicator.py'
'src/slimbookbatterypreferences.py' -> '/usr/share/slimbookbattery/src/slimbookbatterypreferences.py'
'src/slimbookbattery-report.py' -> '/usr/share/slimbookbattery/src/slimbookbattery-report.py'
'src/splash.py' -> '/usr/share/slimbookbattery/src/splash.py'
'src/sudocommands.py' -> '/usr/share/slimbookbattery/src/sudocommands.py'
'src/tdp_utils.py' -> '/usr/share/slimbookbattery/src/tdp_utils.py'
'src/translations' -> '/usr/share/slimbookbattery/src/translations'
'src/translations/README.md' -> '/usr/share/slimbookbattery/src/translations/README.md'
'src/translations/ca' -> '/usr/share/slimbookbattery/src/translations/ca'
'src/translations/ca/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/ca/LC_MESSAGES'
'src/translations/ca/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/ca/LC_MESSAGES/preferences.po'
'src/translations/ca/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/ca/LC_MESSAGES/slimbookbattery.po'
'src/translations/ca/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/ca/LC_MESSAGES/sudocommands.template.po'
'src/translations/cn' -> '/usr/share/slimbookbattery/src/translations/cn'
'src/translations/cn/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/cn/LC_MESSAGES'
'src/translations/cn/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/cn/LC_MESSAGES/preferences.po'
'src/translations/cn/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/cn/LC_MESSAGES/slimbookbattery.po'
'src/translations/cn/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/cn/LC_MESSAGES/sudocommands.template.po'
'src/translations/comparer.py' -> '/usr/share/slimbookbattery/src/translations/comparer.py'
'src/translations/en' -> '/usr/share/slimbookbattery/src/translations/en'
'src/translations/en/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/en/LC_MESSAGES'
'src/translations/en/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/en/LC_MESSAGES/preferences.po'
'src/translations/en/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/en/LC_MESSAGES/slimbookbattery.po'
'src/translations/en/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/en/LC_MESSAGES/sudocommands.template.po'
'src/translations/es' -> '/usr/share/slimbookbattery/src/translations/es'
'src/translations/es/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/es/LC_MESSAGES'
'src/translations/es/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/es/LC_MESSAGES/preferences.po'
'src/translations/es/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/es/LC_MESSAGES/slimbookbattery.po'
'src/translations/es/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/es/LC_MESSAGES/sudocommands.template.po'
'src/translations/gl' -> '/usr/share/slimbookbattery/src/translations/gl'
'src/translations/gl/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/gl/LC_MESSAGES'
'src/translations/gl/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/gl/LC_MESSAGES/preferences.po'
'src/translations/gl/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/gl/LC_MESSAGES/slimbookbattery.po'
'src/translations/gl/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/gl/LC_MESSAGES/sudocommands.template.po'
'src/translations/it' -> '/usr/share/slimbookbattery/src/translations/it'
'src/translations/it/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/it/LC_MESSAGES'
'src/translations/it/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/it/LC_MESSAGES/preferences.po'
'src/translations/it/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/it/LC_MESSAGES/slimbookbattery.po'
'src/translations/it/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/it/LC_MESSAGES/sudocommands.template.po'
'src/translations/nl' -> '/usr/share/slimbookbattery/src/translations/nl'
'src/translations/nl/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/nl/LC_MESSAGES'
'src/translations/nl/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/nl/LC_MESSAGES/preferences.po'
'src/translations/nl/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/nl/LC_MESSAGES/slimbookbattery.po'
'src/translations/nl/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/nl/LC_MESSAGES/sudocommands.template.po'
'src/translations/pt' -> '/usr/share/slimbookbattery/src/translations/pt'
'src/translations/pt/LC_MESSAGES' -> '/usr/share/slimbookbattery/src/translations/pt/LC_MESSAGES'
'src/translations/pt/LC_MESSAGES/preferences.po' -> '/usr/share/slimbookbattery/src/translations/pt/LC_MESSAGES/preferences.po'
'src/translations/pt/LC_MESSAGES/slimbookbattery.po' -> '/usr/share/slimbookbattery/src/translations/pt/LC_MESSAGES/slimbookbattery.po'
'src/translations/pt/LC_MESSAGES/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/pt/LC_MESSAGES/sudocommands.template.po'
'src/translations/slimbookbatteryindicator.template.po' -> '/usr/share/slimbookbattery/src/translations/slimbookbatteryindicator.template.po'
'src/translations/slimbookbatterypreferences.template.po' -> '/usr/share/slimbookbattery/src/translations/slimbookbatterypreferences.template.po'
'src/translations/sudocommands.template.po' -> '/usr/share/slimbookbattery/src/translations/sudocommands.template.po'
'src/updates' -> '/usr/share/slimbookbattery/src/updates'
'src/updates/README' -> '/usr/share/slimbookbattery/src/updates/README'
'src/updates/indicator_extension.sh' -> '/usr/share/slimbookbattery/src/updates/indicator_extension.sh'
'src/utils.py' -> '/usr/share/slimbookbattery/src/utils.py'
'images/balanced_normal.png' -> '/usr/share/slimbookbattery/images/balanced_normal.png'
'images/cc.png' -> '/usr/share/slimbookbattery/images/cc.png'
'images/cross.png' -> '/usr/share/slimbookbattery/images/cross.png'
'images/disabled_normal.png' -> '/usr/share/slimbookbattery/images/disabled_normal.png'
'images/facebook.png' -> '/usr/share/slimbookbattery/images/facebook.png'
'images/GitHub_Logo_White.png' -> '/usr/share/slimbookbattery/images/GitHub_Logo_White.png'
'images/help.png' -> '/usr/share/slimbookbattery/images/help.png'
'images/indicator' -> '/usr/share/slimbookbattery/images/indicator'
'images/indicator/balanced_normal.png' -> '/usr/share/slimbookbattery/images/indicator/balanced_normal.png'
'images/indicator/disabled_normal.png' -> '/usr/share/slimbookbattery/images/indicator/disabled_normal.png'
'images/indicator/normal.png' -> '/usr/share/slimbookbattery/images/indicator/normal.png'
'images/indicator/performance_normal.png' -> '/usr/share/slimbookbattery/images/indicator/performance_normal.png'
'images/insta.png' -> '/usr/share/slimbookbattery/images/insta.png'
'images/interface' -> '/usr/share/slimbookbattery/images/interface'
'images/interface/btn1.png' -> '/usr/share/slimbookbattery/images/interface/btn1.png'
'images/interface/btn2.png' -> '/usr/share/slimbookbattery/images/interface/btn2.png'
'images/interface/btn3.png' -> '/usr/share/slimbookbattery/images/interface/btn3.png'
'images/interface/current-tab.png' -> '/usr/share/slimbookbattery/images/interface/current-tab.png'
'images/interface/tab.png' -> '/usr/share/slimbookbattery/images/interface/tab.png'
'images/loading.gif' -> '/usr/share/slimbookbattery/images/loading.gif'
'images/logo.png' -> '/usr/share/slimbookbattery/images/logo.png'
'images/normal.png' -> '/usr/share/slimbookbattery/images/normal.png'
'images/performance_normal.png' -> '/usr/share/slimbookbattery/images/performance_normal.png'
'images/slimbookbattery-header-1.png' -> '/usr/share/slimbookbattery/images/slimbookbattery-header-1.png'
'images/slimbookbattery-header-2.png' -> '/usr/share/slimbookbattery/images/slimbookbattery-header-2.png'
'images/slimbookbattery-header-3.png' -> '/usr/share/slimbookbattery/images/slimbookbattery-header-3.png'
'images/slimbookbattery-header-4.png' -> '/usr/share/slimbookbattery/images/slimbookbattery-header-4.png'
'images/slimbookbattery-header.png' -> '/usr/share/slimbookbattery/images/slimbookbattery-header.png'
'images/slimbookbattery-header-rev.png' -> '/usr/share/slimbookbattery/images/slimbookbattery-header-rev.png'
'images/slimbookbattery.png' -> '/usr/share/slimbookbattery/images/slimbookbattery.png'
'images/slimbook_splash.png' -> '/usr/share/slimbookbattery/images/slimbook_splash.png'
'images/splash.gif' -> '/usr/share/slimbookbattery/images/splash.gif'
'images/stack-background.png' -> '/usr/share/slimbookbattery/images/stack-background.png'
'images/twitter.png' -> '/usr/share/slimbookbattery/images/twitter.png'
'images/warning.png' -> '/usr/share/slimbookbattery/images/warning.png'
'images/slimbookbattery.png' -> '/usr/share/pixmaps/slimbookbattery.png'
cp: target '/usr/share/slimbookbattery/custom/': No such file or directory
cp: target '/usr/share/slimbookbattery/default/': No such file or directory
'policykit/com.ubuntu.pkexec.slimbookbattery.policy' -> '/usr/share/polkit-1/actions/com.ubuntu.pkexec.slimbookbattery.policy'
'debian/changelog' -> '/usr/share/slimbookbattery/src/changelog'
'LICENSE' -> '/usr/share/slimbookbattery/LICENSE'
...Done copying contents!

Creating binary symlinks...
'/usr/share/slimbookbattery/bin/slimbookbattery' -> '/usr/bin/slimbookbattery'
'/usr/share/slimbookbattery/bin/slimbookbattery-pkexec' -> '/usr/bin/slimbookbattery-pkexec'
...Done creating binary symlinks!

Running post installation script and applying translations...
Cannot open log file /var/slimbookbattery.log, using /tmp/slimbookbattery.log
Cannot open log file /var/slimbookbattery.log, using /tmp/slimbookbattery.log
Traceback (most recent call last):
  File "/usr/share/slimbookbattery/src/check_config.py", line 175, in <module>
    main()
  File "/usr/share/slimbookbattery/src/check_config.py", line 50, in main
    set_ownership(UPDATES_DIR)
  File "/usr/share/slimbookbattery/src/check_config.py", line 66, in set_ownership
    os.chown(dir_path, uid, gid)
PermissionError: [Errno 1] Operation not permitted: '/usr/share/slimbookbattery/src/updates'
chmod: changing permissions of '/usr/share/slimbookbattery/src/service/slimbookbatteryservice.sh': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/updates/indicator_extension.sh': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/ac_power.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/check_config.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/slimbookbatteryindicator.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/slimbookbatterypreferences.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/slimbookbattery-report.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/splash.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/sudocommands.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/tdp_utils.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/translations/comparer.py': Operation not permitted
chmod: changing permissions of '/usr/share/slimbookbattery/src/utils.py': Operation not permitted
Synchronizing state of tlp.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable tlp
...Done installing SlimbookBattery!
````

Any tip?

**Comment by siddhpant** [comment]
Kali is not Debian. It is a different distro based on Debian.

Also, I did not encounter this on my Debian machine and can run Slimbook Battery successfully everyday. Also, the Open Build Service package is outdated.

Edit: Just saw the linked PR, since it auto-starts for me it was working. Sorry for the noise. But you should have mentioned the output.

**Comment by siddhpant** [comment]
>  Installing it from the repo gives following output:

Please run it as root. It should ask. Will send a fix.

**Comment by siddhpant** [comment]
#100 should fix installation.
